server:
  port: 5000

naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  client:
    id: 
    secret: 

naver-cloud-sms:
  accesskey: 
  secretKey: 
  serviceId: 
  senderPhone: 

spring:
  datasource:
    url: 
    username: 
    password: 
  sql:
    init:
      mode: always # spring.sql.init.mode = always로 줘야 data.sql이 실행됨
  jpa:
    show-sql: true # SQL 로그 출력
    properties:
      hibernate:
        format_sql: true # SQL 로그 출력
    generate-ddl: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

cloud:
  aws:
    s3:
      bucket: 
    credentials:
      access-key: 
      secret-key: 
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
