server:
  port: 5000

naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  client:
    id: 9MzYRB5D2ltx9F13zISx
    secret: FS49jYJ5VV

naver-cloud-sms:
  accesskey: 17fzA5KYVlFlhBhQpAK5
  secretKey: yTsepyynNwTFolTCExmlSoa3PAjxhAIY16Om1t5h
  serviceId: ncp:sms:kr:316018634333:prj_test
  senderPhone: 01048232132

spring:
  datasource:
    url: jdbc:mysql://awseb-e-w3gtv3gpkm-stack-awsebrdsdatabase-bpylayofzyd7.cshj9sav9na0.ap-northeast-2.rds.amazonaws.com:3306/ebdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8 # [] 안에 본인 db이름 써주세요 []는 지우세요
    username: admin # 설정했던 user 명
    password: xnTja*1234 # 설정했던 password
  sql:
    init:
      mode: always # spring.sql.init.mode = always로 줘야 data.sql이 실행됨
  jpa:
    show-sql: true # SQL 로그 출력
    properties:
      hibernate:
        format_sql: true # SQL 로그 출력
    generate-ddl: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

cloud:
  aws:
    s3:
      bucket: elasticbeanstalk-ap-northeast-2-028662638933
    credentials:
      access-key: AKIAQNLDNFFKVHVFOUE5
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false